asm
ikriushenkov/cpp-first-term pull request #1
Opened 2020-06-26 01:23 UTC by ikriushenkov

2020-06-26 14:14 UTC, kt-cpp requested changes

2020-06-26 14:14 UTC, kt-cpp commented on asm/mul.asm
> +                lea             r13, [rcx]
`move r13 rcx` ?)

2020-06-26 14:14 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256
Лучше бы длину передавать в функцию, а не хардкодить

2020-06-26 14:14 UTC, kt-cpp commented on asm/mul.asm
> +                lea             r13, [rcx]
Таких мест несколько

2020-06-26 14:14 UTC, kt-cpp commented on asm/mul.asm
> +mul_long_short:
Потенциально длина ответа этой функции `rcx + 1`, однако она пишет только первые `rcx` qword'ов. Ты точно к этому готов в своих вызовах?

2020-06-30 00:28 UTC, ikriushenkov commented on asm/mul.asm
> +                lea             r13, [rcx]
Исправил

2020-06-30 00:28 UTC, ikriushenkov commented on asm/mul.asm
> +                mov             rcx, 256
Исправил

2020-06-30 00:31 UTC, ikriushenkov commented on asm/mul.asm
> +mul_long_short:
Все промежуточные вычисления ответа происходят в 256 шортах, когда тут макс значение будет иметь 129, так что вроде бы все хорошо. Или я не понял вопроса.

2020-06-30 11:39 UTC, kt-cpp commented on asm/mul.asm
> +                mov             rcx, 256
И да и нет, читай другие комменты

2020-06-30 11:41 UTC, kt-cpp commented on asm/mul.asm
> +mul_long_short:
Это не то, что от вас хотят. Вы должны оперировать аргументами длины Х, а ответ получаться длины 2Х, что например делает сама ассемблерная команда mul. Делать всю арифметику в 256 это чит, которые проходит тесты, но не отражает суть дз

2020-06-30 11:42 UTC, kt-cpp requested changes
Ответил в комменте выше про 256-значную арфметику

2020-07-01 21:59 UTC, kt-cpp commented on asm/mul.asm
> +                call            copy_r8_to_rdi
А почему бы не скопировать и явно сделать последний (старший) нулем?

2020-07-01 22:01 UTC, kt-cpp commented on asm/mul.asm
> +                sub             rsp, 5 * size * 8 + 8
Выдели `128 * 8 + 8` в теле функции `mul_long_long` и потом не забудь подчистить за собой

2020-07-01 22:03 UTC, kt-cpp commented on asm/mul.asm
> +                lea             r13, [r13 + 8]
вот эти `lea` можно сделать в конце цикла, чтобы лучше выглядело

2020-07-01 22:03 UTC, kt-cpp commented on asm/mul.asm
> +                clc
Зачем `clc`

2020-07-01 22:05 UTC, kt-cpp requested changes
Почти норм

2020-07-01 22:48 UTC, ikriushenkov commented on asm/mul.asm
> +                call            copy_r8_to_rdi
Не уверен, что понял, но что-то исправил. Строчек стало меньше

2020-07-01 22:49 UTC, ikriushenkov commented on asm/mul.asm
> +                sub             rsp, 5 * size * 8 + 8
Сделал

2020-07-01 22:49 UTC, ikriushenkov commented on asm/mul.asm
> +                lea             r13, [r13 + 8]
Сделал

2020-07-01 22:49 UTC, ikriushenkov commented on asm/mul.asm
> +                clc
Удалил

2020-07-02 15:15 UTC, kt-cpp commented on asm/mul.asm
> +                dec             rcx
Это слегка абуз ...

Но раз в контракте это учитывается, то ладно (но в будущем так не делай)

2020-07-02 15:16 UTC, kt-cpp approved these changes
Пойдет

2020-07-02 15:16 UTC, merged