Vector
ikriushenkov/cpp-first-term pull request #3
Opened 2020-07-01 23:56 UTC by ikriushenkov

2020-07-02 14:02 UTC, kt-cpp requested changes
грубых ошибок нет, просто поработать на десигном

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +vector <T>::vector() {
vector() : ... {} + правильный порядок

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +    data_ = nullptr;
чтобы такое не плодить, здесь можно сделать так: vector(vector const& other) : vector() {}

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +typename vector<T>::iterator vector <T>::data() {
ты возвращаешь не итератор, хоть тип и совпадает

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +    if (capacity_ == 0) {
[style] reserve(тернарник)

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +        new(data_ + size_)T(data_[size_ - 1]);
2 странных new. может лучше push_back(val) ?

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +            data_[i] = data_[i - 1];
эти присваивания принесут потенциальное копирование объектов, лучше свап

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +    size_t it = index - data_;
нужен правильный тип для поинтер арифметики

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +        data_[i - d] = data_[i];
снова присваивания и тип для поинтеров

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +    return insert(static_cast<T const*>(index), val);
для erase и insert достаточноперегрузок по const_iterator. от этого лучше избавиться, чтобы не плодить гадости

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +        destroy_data(to, i);
странно давать для copy возможность удалить твой буффер. ок если просто деструкторы вызвать, но operator delete внутри destroy плохой

2020-07-02 14:02 UTC, kt-cpp commented on vector/vector.h
> +        destroy_data(to, i);
[design] эта функция больше похожа на метод new_buffer (который копипаста внутри reserve и shrink_to_fit). мб сделать его?

2020-07-02 15:34 UTC, ikriushenkov commented on vector/vector.h
> +vector <T>::vector() {
Исправил

2020-07-02 15:34 UTC, ikriushenkov commented on vector/vector.h
> +    data_ = nullptr;
Сделал как в vector()

2020-07-02 15:35 UTC, ikriushenkov commented on vector/vector.h
> +typename vector<T>::iterator vector <T>::data() {
Исправил

2020-07-02 15:35 UTC, ikriushenkov commented on vector/vector.h
> +    if (capacity_ == 0) {
Исправил

2020-07-02 15:35 UTC, ikriushenkov commented on vector/vector.h
> +        new(data_ + size_)T(data_[size_ - 1]);
Исправил

2020-07-02 15:35 UTC, ikriushenkov commented on vector/vector.h
> +            data_[i] = data_[i - 1];
Исправил

2020-07-02 15:35 UTC, ikriushenkov commented on vector/vector.h
> +    size_t it = index - data_;
Везде где нашел исправил

2020-07-02 15:36 UTC, ikriushenkov commented on vector/vector.h
> +        data_[i - d] = data_[i];
Исправил

2020-07-02 15:36 UTC, ikriushenkov commented on vector/vector.h
> +    return insert(static_cast<T const*>(index), val);
Убрал

2020-07-02 15:37 UTC, ikriushenkov commented on vector/vector.h
> +        destroy_data(to, i);
Сделал new_buffer, теперь копипасты нет, но copy оставил. Убрал в ней operator delete

2020-07-02 19:28 UTC, kt-cpp commented on vector/vector.h
> +    if (capacity_ == 0) {
ты сделал что-то странное

2020-07-02 19:29 UTC, kt-cpp commented on vector/vector.h
> +    reserve(other.size_);
таки здесь просто new_buffer ?

2020-07-02 19:29 UTC, kt-cpp commented on vector/vector.h
> +    data_ = nullptr;
перечитай еще раз, даже код написал

2020-07-02 19:30 UTC, kt-cpp commented on vector/vector.h
> +        destroy_data(to, i);
на самом деле copy все также удалит буффер в случае неудачи, но т.к. он вызывается только из new_buffer то ок

2020-07-02 19:31 UTC, kt-cpp requested changes
исправь миноры

2020-07-02 20:26 UTC, ikriushenkov commented on vector/vector.h
> +    data_ = nullptr;
Теперь сделал именно так

2020-07-02 20:27 UTC, ikriushenkov commented on vector/vector.h
> +    if (capacity_ == 0) {
Теперь вроде норм

2020-07-02 20:27 UTC, ikriushenkov commented on vector/vector.h
> +    reserve(other.size_);
Изменил

2020-07-02 20:56 UTC, kt-cpp requested changes
Остались лишь миноры

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +#include <iostream>
[minor] Зачем он тут?

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +    void copy(T* from, T* to, size_t size);
[minor] А почему не `static`?

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +    void destroy_data(T* data, size_t capacity);
[minor] А почему не `static`?

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +vector <T>::vector() : data_(nullptr), size_(0), capacity_(0) {}
[minor] Тут и ещё много где лишний пробел перед треугольными скобками

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +    }
[minor] Почему бы не переиспользовать `destroy`?

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +    std::swap(data_, other.data_);
[note] Лучше сделать `using std::swap`, а потом вызывать его без указания `namespace`, привнеся этим другие свапы не только из `std`

2020-07-02 20:56 UTC, kt-cpp commented on vector/vector.h
> +    size_ -= d;
[minor] `pop_back`?)

2020-07-02 23:39 UTC, ikriushenkov commented on vector/vector.h
> +#include <iostream>
Чтобы были size_t и swap. Изменил на cstddef (size_t) и algorithm (swap)

2020-07-02 23:39 UTC, ikriushenkov commented on vector/vector.h
> +    void copy(T* from, T* to, size_t size);
Не знаю. Исправил

2020-07-02 23:40 UTC, ikriushenkov commented on vector/vector.h
> +    void destroy_data(T* data, size_t capacity);
Теперь static

2020-07-02 23:40 UTC, ikriushenkov commented on vector/vector.h
> +vector <T>::vector() : data_(nullptr), size_(0), capacity_(0) {}
Убрал все пробелы, которые были не нужны

2020-07-02 23:40 UTC, ikriushenkov commented on vector/vector.h
> +    }
Исправил

2020-07-02 23:41 UTC, ikriushenkov commented on vector/vector.h
> +    std::swap(data_, other.data_);
Сделал так

2020-07-02 23:41 UTC, ikriushenkov commented on vector/vector.h
> +    size_ -= d;
Да

2020-07-03 06:13 UTC, kt-cpp commented on vector/vector.h
> +    std::swap(data_, other.data_);
using std::swap в самом начале файла лишний

2020-07-03 06:13 UTC, kt-cpp approved these changes

2020-07-03 06:14 UTC, merged